### ISSUE TITLE
Use GitHub actions to build executables

### ISSUE THREAD

**Issue by Al2Klimov** [Al2Klimov/trainee-go-sort#29]
... for all ["valid combinations of $GOOS and $GOARCH"](https://golang.org/doc/install/source#environment).

* [x] Figure out how to build executables
* [x] ... for a specific architecture
* [x] ... and OS
* [x] Actually build them via GitHub actions

**Comment by justinmueller05082000** [comment]
To build an executable you'll need Go installed. You can build an executable with ` go build <name/path>`.

To build an executable for a specific architecture and OS use `env GOOS=<OS> GOARCH=<architecture> go build <name/path>`.

Here's a list for all valid combinations of $GOOS and $GOARCH:

![Screenshot from 2020-04-20 17-03-15](https://user-images.githubusercontent.com/55092455/79766987-03456a00-8329-11ea-811c-bfd43cc072a0.png)

You can use the `-o` flag to specify a different name or location for the executable.

**Comment by Al2Klimov** [comment]
How do I build `./sort.openbsd-386` being the sort executable for 32-bit OpenBSD while being inside this (cloned) repo?

**Comment by justinmueller05082000** [comment]
GOOS=openbsd GOARCH=386 go build -o sort.openbsd-386 .
